apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::512533103985:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-14E6G18W21201
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::512533103985:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-11T22:34:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "844"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bcce3d80-cecd-4004-b673-e6c28d0108c8
